(()=>{'use strict';
const $=id=>document.getElementById(id),num=id=>Number($(id)?.value||0),clamp=(x,a,b)=>Math.min(b,Math.max(a,x)),clone=o=>JSON.parse(JSON.stringify(o)),fmt=x=>`${x>=0?'+':''}${x.toFixed(2)}%`,esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const DT=[['basic','普攻'],['heavy','重击'],['skill','共鸣技能'],['liberation','共鸣解放'],['coordinated','协同攻击'],['other','其他']];
const SS=[['','— 无 —'],['critRate','暴击率 %'],['critDmg','暴击伤害 %'],['atkPct','攻击力 %'],['flatAtk','固定攻击'],['hpPct','生命值 %'],['flatHp','固定生命'],['defPct','防御力 %'],['flatDef','固定防御'],['energyRegen','共鸣效率 %'],['basicDmg','普攻伤害 %'],['heavyDmg','重击伤害 %'],['skillDmg','共鸣技能伤害 %'],['liberationDmg','共鸣解放伤害 %']],SL=Object.fromEntries(SS);
const FALLBACK=['景燃','清宵','穗穗','秧秧·玄翎','洛瑟菈','达妮娅','绯雪','西格莉卡','陆·赫斯','爱弥斯','莫宁','琳奈','千咲','仇远','嘉贝莉娜','尤诺','奥古斯塔','弗洛洛','露帕','卡提希娅','夏空','赞妮','坎特蕾拉','布兰特','菲比','洛可可','珂莱塔','椿','守岸人','相里要','折枝','长离','今汐','吟霖','忌炎','秧秧','散华','渊武','秋水','莫特斐','丹瑾','桃祈','维里奈','凌阳','卡卡罗','鉴心','安可','漂泊者'].map((name,i)=>({id:`fallback-${i}`,name,image:''}));
let roster=FALLBACK,selectedCharacter=null;
const blankLine=()=>({type:'',value:0});
const blankEcho=(cost=4)=>({cost,main:[blankLine(),blankLine()],sub:[blankLine(),blankLine(),blankLine(),blankLine(),blankLine()]});
let M={echoes:[blankEcho(4),blankEcho(3),blankEcho(3),blankEcho(1),blankEcho(1)],candidate:blankEcho(4),rolls:{critRate:8.4,critDmg:16.8,statPct:9,dmg:9,flatAtk:45,flatHp:450,flatDef:55}};
function opts(a,v){return a.map(([x,l])=>`<option value="${x}" ${String(x)===String(v)?'selected':''}>${l}</option>`).join('')}
async function loadRoster(){try{const r=await fetch('/wuwa/data/characters.json',{cache:'no-store'});if(!r.ok)throw 0;const j=await r.json();const arr=Array.isArray(j)?j:j.characters;if(!Array.isArray(arr)||!arr.length)throw 0;roster=arr.filter(x=>x&&x.name).map((x,i)=>({id:String(x.id||i),name:String(x.name).trim(),image:x.image||x.icon||x.cover||''}));$('rosterSource').textContent=`库街区角色库 · ${roster.length} 名角色`;}catch(e){roster=FALLBACK;$('rosterSource').textContent='角色库本地快照';}renderCharacters()}
function avatar(c){if(c?.image)return `<span class="portrait"><img src="${esc(c.image)}" alt="${esc(c.name)}" loading="lazy" referrerpolicy="no-referrer" onerror="this.parentElement.textContent='${esc(c.name.slice(0,1))}'"></span>`;return `<span class="portrait placeholder">${esc((c?.name||'?').slice(0,1))}</span>`}
function renderCharacters(filter=''){const q=filter.trim().toLowerCase();$('characterGrid').innerHTML=roster.filter(c=>!q||c.name.toLowerCase().includes(q)).map(c=>`<button class="character-card" data-char-id="${esc(c.id)}" type="button">${avatar(c)}<span>${esc(c.name)}</span></button>`).join('')}
function selectCharacter(c){selectedCharacter=c;$('characterPick').innerHTML=`${avatar(c)}<span class="pick-copy"><b id="characterName">${esc(c.name)}</b><small id="rosterSource">库街区角色库</small></span>`;$('characterBrowser').hidden=true}
function initTypes(){$('typeBonusGrid').innerHTML=DT.map(([k,l])=>`<div class="type-bonus-row"><span>${l}</span><label>加成 %<input id="dmg_${k}" type="number" value="0" step="0.1"></label><label>Amplify %<input id="amp_${k}" type="number" value="0" step="0.1"></label></div>`).join('')}
function lineRows(lines){return lines.map((r,i)=>`<div class="echo-row" data-i="${i}"><select class="echo-type">${opts(SS,r.type)}</select><input class="echo-value" type="number" step="0.1" value="${r.value||0}" aria-label="数值"></div>`).join('')}
function echoCards(){$('equippedEchoes').innerHTML=M.echoes.map((e,i)=>`<div class="echo-card" data-echo="${i}"><div class="echo-card-head"><b>声骸 ${i+1}</b><select class="cost-select echo-cost"><option value="4" ${e.cost===4?'selected':''}>4 COST</option><option value="3" ${e.cost===3?'selected':''}>3 COST</option><option value="1" ${e.cost===1?'selected':''}>1 COST</option></select></div><div class="echo-section-label">主词条</div><div class="main-rows">${lineRows(e.main)}</div><div class="echo-section-label">副词条</div><div class="sub-rows">${lineRows(e.sub)}</div><div class="echo-mini-score"><span>本站边际评分</span><strong id="miniScore${i}">—</strong></div></div>`).join('')}
function candidateRows(){$('candidateMainRows').innerHTML=lineRows(M.candidate.main);$('candidateSubRows').innerHTML=lineRows(M.candidate.sub)}
function pullEchoes(){document.querySelectorAll('.echo-card').forEach(card=>{const i=+card.dataset.echo,e=M.echoes[i];e.cost=+card.querySelector('.echo-cost').value;e.main=[...card.querySelectorAll('.main-rows .echo-row')].map(row=>({type:row.querySelector('.echo-type').value,value:+row.querySelector('.echo-value').value||0}));e.sub=[...card.querySelectorAll('.sub-rows .echo-row')].map(row=>({type:row.querySelector('.echo-type').value,value:+row.querySelector('.echo-value').value||0}))});M.candidate.cost=+($('candidateCost').value||4);M.candidate.main=[...$('candidateMainRows').querySelectorAll('.echo-row')].map(row=>({type:row.querySelector('.echo-type').value,value:+row.querySelector('.echo-value').value||0}));M.candidate.sub=[...$('candidateSubRows').querySelectorAll('.echo-row')].map(row=>({type:row.querySelector('.echo-type').value,value:+row.querySelector('.echo-value').value||0}))}
function state(){const td={},ta={};DT.forEach(([k])=>{td[k]=num('dmg_'+k);ta[k]=num('amp_'+k)});return{base:{atk:num('baseAtk'),hp:num('baseHp'),def:num('baseDef')},total:{atk:num('totalAtk'),hp:num('totalHp'),def:num('totalDef')},critRate:num('critRate'),critDmg:num('critDmg'),energyRegen:num('energyRegen'),globalDmg:num('globalDmg'),globalAmp:num('globalAmp'),typeDmg:td,typeAmp:ta}}
function sub(s,t,v,sg=1){v*=sg;if(!t||!v)return s;if(t==='atkPct')s.total.atk+=s.base.atk*v/100;else if(t==='flatAtk')s.total.atk+=v;else if(t==='hpPct')s.total.hp+=s.base.hp*v/100;else if(t==='flatHp')s.total.hp+=v;else if(t==='defPct')s.total.def+=s.base.def*v/100;else if(t==='flatDef')s.total.def+=v;else if(t==='critRate')s.critRate+=v;else if(t==='critDmg')s.critDmg+=v;else if(t==='energyRegen')s.energyRegen+=v;else if(t==='basicDmg')s.typeDmg.basic+=v;else if(t==='heavyDmg')s.typeDmg.heavy+=v;else if(t==='skillDmg')s.typeDmg.skill+=v;else if(t==='liberationDmg')s.typeDmg.liberation+=v;return s}
function applyEcho(s,e,sg=1){[...(e?.main||[]),...(e?.sub||[])].forEach(r=>sub(s,r.type,+r.value||0,sg));return s}
function combat(s){s=clone(s);s.total.atk+=s.base.atk*num('selfAtkPct')/100;s.critRate+=num('selfCritRate');s.critDmg+=num('selfCritDmg');s.globalDmg+=num('selfDmg');s.globalAmp+=num('selfAmp');const t=$('primaryDamageType').value;s.typeDmg[t]=(s.typeDmg[t]||0)+num('selfTypeDmg');return s}
function factorOne(s,type){s=combat(s);const scaler=$('scaler').value;const stat=Math.max(1e-6,s.total[scaler]),dmg=Math.max(1e-6,1+(s.globalDmg+(s.typeDmg[type]||0))/100),amp=Math.max(1e-6,1+(s.globalAmp+(s.typeAmp[type]||0))/100),cr=clamp(s.critRate/100,0,1),cd=Math.max(1,s.critDmg/100),crit=1+cr*(cd-1);return stat*dmg*amp*crit}
function factor(s){const t=$('primaryDamageType').value,q=clamp(num('primaryShare')/100,0,1);const a=factorOne(s,t),b=factorOne(s,'other');return q*a+(1-q)*b}
function compare(a,b){return(factor(b)/factor(a)-1)*100}
function singleGain(base,t,v){const c=clone(base);sub(c,t,v);return compare(base,c)}
function standardCandidates(base){const r=M.rolls;const type=$('primaryDamageType').value;const typeKey={basic:'basicDmg',heavy:'heavyDmg',skill:'skillDmg',liberation:'liberationDmg'}[type];const scaler=$('scaler').value;const scalePct=scaler==='atk'?'atkPct':scaler==='hp'?'hpPct':'defPct';const scaleFlat=scaler==='atk'?'flatAtk':scaler==='hp'?'flatHp':'flatDef';const flatVal=scaler==='atk'?r.flatAtk:scaler==='hp'?r.flatHp:r.flatDef;const scaleLabel=scaler==='atk'?'大攻击':scaler==='hp'?'大生命':'大防御';const flatLabel=scaler==='atk'?'小攻击':scaler==='hp'?'小生命':'小防御';const rows=[['critRate',r.critRate,`暴击 ${r.critRate}%`],['critDmg',r.critDmg,`暴伤 ${r.critDmg}%`],[scalePct,r.statPct,`${scaleLabel} ${r.statPct}%`],[scaleFlat,flatVal,`${flatLabel} ${flatVal}`]];if(typeKey)rows.push([typeKey,r.dmg,`${SL[typeKey]} ${r.dmg}%`]);return rows.map(([type,val,label])=>({type,val,label,value:singleGain(base,type,val)})).sort((a,b)=>b.value-a.value)}
function marginalScore(full,e,subOnly=true){const lines=(subOnly?e.sub:[...e.main,...e.sub]).filter(r=>r.type&&+r.value);if(!lines.length)return{score:0,equiv:0,reference:0};const std=standardCandidates(full);const ref=Math.max(.000001,std[0]?.value||0)/100;let equiv=0;lines.forEach(line=>{const no=clone(full);sub(no,line.type,+line.value,-1);const g=Math.max(-.999999,compare(no,full)/100);equiv+=Math.log1p(g)/Math.log1p(ref)});return{score:equiv/5*100,equiv,reference:ref*100}}
function grade(score){if(score>=100)return'SSS';if(score>=90)return'SS';if(score>=80)return'S';if(score>=65)return'A';if(score>=50)return'B';return'C'}
function bars(root,a){const mx=Math.max(.01,...a.map(x=>Math.abs(x.value)));root.innerHTML=a.map(x=>`<div class="bar-row ${x.value<0?'negative':''}"><div class="bar-label">${esc(x.label)}</div><div class="bar-track"><div class="bar-fill" style="width:${Math.min(100,Math.abs(x.value)/mx*100)}%"></div></div><div class="bar-value">${fmt(x.value)}</div></div>`).join('')||'<div class="micro">暂无数据。</div>'}
function rollUI(){const r=M.rolls;$('rollControls').innerHTML=[['critRate','标准暴击 %'],['critDmg','标准暴伤 %'],['statPct','标准属性%'],['dmg','标准类型伤 %'],['flatAtk','标准小攻击'],['flatHp','标准小生命'],['flatDef','标准小防御']].map(([k,l])=>`<label>${l}<input class="roll-input" data-roll="${k}" type="number" step="0.1" value="${r[k]}"></label>`).join('')}
function boundaries(cur){const r=M.rolls,cr=clamp((cur.critRate+num('selfCritRate'))/100,0,1),cd=(cur.critDmg+num('selfCritDmg'))/100,gCD=singleGain(cur,'critDmg',r.critDmg),gCR=singleGain(cur,'critRate',r.critRate),std=standardCandidates(cur),scale=std.find(x=>['atkPct','hpPct','defPct'].includes(x.type)),gScale=scale?.value||0;$('boundaryCards').innerHTML=`<div class="boundary-card"><span>战斗态双暴</span><strong>${(cr*100).toFixed(1)} / ${(cd*100).toFixed(1)}</strong><span>标准暴击 ${fmt(gCR)}；标准暴伤 ${fmt(gCD)}。</span></div><div class="boundary-card"><span>爆伤 vs 主要属性%</span><strong>${gCD>gScale?'爆伤当前更高':'主要属性%当前更高'}</strong><span>标准暴伤 ${fmt(gCD)} · ${esc(scale?.label||'主要属性')} ${fmt(gScale)}。自拐爆伤越高，继续堆爆伤的边际价值越容易下滑。</span></div><div class="boundary-card"><span>共鸣链记录</span><strong>${$('chainLevel').value} 链</strong><span>面板内永久效果由当前总值承担；战斗中临时效果由上方修正项承担。</span></div>`}
function calculate(){pullEchoes();const cur=state();const slot=+$('replaceSlot').value;const base=clone(cur);applyEcho(base,M.echoes[slot],-1);const candidate=clone(base);applyEcho(candidate,M.candidate,1);const gain=compare(cur,candidate);$('overallGain').textContent=fmt(gain);const cscore=marginalScore(candidate,M.candidate,true);$('candidateScore').textContent=cscore.score.toFixed(1);const cc=combat(cur),cr=clamp(cc.critRate/100,0,1),cd=Math.max(1,cc.critDmg/100);$('critFactor').textContent=(1+cr*(cd-1)).toFixed(4);$('critState').textContent=`${cc.critRate.toFixed(1)}% CR / ${cc.critDmg.toFixed(1)}% CD`;const std=standardCandidates(cur);$('bestStandard').textContent=std[0]?.label||'—';bars($('standardBars'),std);const lines=M.candidate.sub.filter(r=>r.type&&r.value).map(r=>{const no=clone(candidate);sub(no,r.type,r.value,-1);return{label:`${SL[r.type]||r.type} ${r.value}`,value:compare(no,candidate)}});bars($('lineMarginals'),lines);const cards=M.echoes.map((e,i)=>{const without=clone(cur);applyEcho(without,e,-1);const contribution=compare(without,cur);const sc=marginalScore(cur,e,true),g=grade(sc.score),mini=$('miniScore'+i);if(mini)mini.textContent=sc.score.toFixed(1);return`<div class="score-card"><div class="score-card-head"><div><small>声骸 ${i+1} · ${e.cost} COST</small><strong>${sc.score.toFixed(1)}</strong></div><span class="grade">${g}</span></div><div class="score-contrib">整只声骸相对“卸下它”贡献 ${fmt(contribution)} · 等效最优平均词条 ${sc.equiv.toFixed(2)} 条</div></div>`});$('echoScoreCards').innerHTML=cards.join('');boundaries(cur)}
function bind(){$('characterPick').onclick=()=>{$('characterBrowser').hidden=false;renderCharacters($('characterSearch').value);$('characterBrowser').scrollIntoView({behavior:'smooth',block:'nearest'})};$('closeCharacterBrowser').onclick=()=>{$('characterBrowser').hidden=true};$('characterSearch').oninput=e=>renderCharacters(e.target.value);$('characterGrid').onclick=e=>{const b=e.target.closest('[data-char-id]');if(!b)return;const c=roster.find(x=>x.id===b.dataset.charId);if(c)selectCharacter(c)};$('chainLevel').onchange=()=>{$('chainLabel').textContent=`${$('chainLevel').value} 链`;calculate()};$('candidateCost').onchange=e=>{M.candidate.cost=+e.target.value;calculate()};$('calculateBtn').onclick=calculate;$('resetStatsBtn').onclick=()=>{[['baseAtk',950],['totalAtk',2300],['baseHp',15000],['totalHp',21000],['baseDef',1200],['totalDef',1500],['critRate',75],['critDmg',250],['energyRegen',125],['globalDmg',60],['globalAmp',0],['selfAtkPct',0],['selfCritRate',0],['selfCritDmg',0],['selfDmg',0],['selfTypeDmg',0],['selfAmp',0]].forEach(([id,v])=>$(id).value=v);calculate()};document.body.addEventListener('input',e=>{if(e.target.matches('input,select')){if(e.target.matches('.roll-input'))M.rolls[e.target.dataset.roll]=+e.target.value||0;calculate()}});document.body.addEventListener('change',e=>{if(e.target.matches('.echo-cost'))calculate()})}
initTypes();echoCards();candidateRows();rollUI();bind();loadRoster().then(calculate);calculate();
})();