(()=>{'use strict';
const $=id=>document.getElementById(id),num=id=>Number($(id)?.value||0),clamp=(x,a,b)=>Math.min(b,Math.max(a,x)),clone=o=>JSON.parse(JSON.stringify(o)),fmt=x=>`${x>=0?'+':''}${x.toFixed(2)}%`,esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const DT=[['basic','普攻'],['heavy','重击'],['skill','共鸣技能'],['liberation','共鸣解放'],['coordinated','协同攻击'],['echo','声骸技能'],['other','其他']],SC=[['atk','ATK'],['hp','HP'],['def','DEF']];
const SS=[['','— 无 —'],['critRate','暴击率 %'],['critDmg','暴击伤害 %'],['atkPct','攻击力 %'],['flatAtk','固定攻击'],['hpPct','生命值 %'],['flatHp','固定生命'],['defPct','防御力 %'],['flatDef','固定防御'],['energyRegen','共鸣效率 %'],['basicDmg','普攻伤害 %'],['heavyDmg','重击伤害 %'],['skillDmg','共鸣技能伤害 %'],['liberationDmg','共鸣解放伤害 %']],SL=Object.fromEntries(SS);
const BE=[['atkPct','攻击力 %'],['flatAtk','固定攻击'],['hpPct','生命值 %'],['flatHp','固定生命'],['defPct','防御力 %'],['flatDef','固定防御'],['critRate','暴击率 %'],['critDmg','暴击伤害 %'],['energyRegen','共鸣效率 %'],['dmgBonus','伤害加成 %'],['amplify','Amplify / 加深 %']];
const FALLBACK=['景燃','清宵','穗穗','秧秧·玄翎','洛瑟菈','达妮娅','绯雪','西格莉卡','陆·赫斯','爱弥斯','莫宁','琳奈','卜灵','千咲','仇远','嘉贝莉娜','尤诺','奥古斯塔','弗洛洛','露帕','卡提希娅','夏空','赞妮','坎特蕾拉','布兰特','菲比','洛可可','珂莱塔','灯灯','椿','釉瑚','守岸人','相里要','折枝','长离','今汐','吟霖','忌炎','秧秧','散华','渊武','秋水','莫特斐','丹瑾','桃祈','维里奈','凌阳','卡卡罗','鉴心','安可','漂泊者'].map((name,i)=>({id:`fallback-${i}`,name,image:'',source:'fallback'}));
let roster=FALLBACK, pickSlot='carry', advanced=false;
let M={oldEcho:[{type:'critRate',value:8.1},{type:'critDmg',value:16.2},{type:'atkPct',value:8.6},{type:'skillDmg',value:8.6},{type:'flatAtk',value:40}],newEcho:[{type:'critRate',value:9.3},{type:'critDmg',value:18.6},{type:'atkPct',value:10.1},{type:'skillDmg',value:10.1},{type:'flatAtk',value:50}],buffs:[{id:'b1',source:'mate3',name:'攻击 Buff',effect:'atkPct',value:20,target:'all'}],segments:[{id:'s1',name:'主要输出',type:'skill',scaler:'atk',share:100,canCrit:true,buffs:['b1']}],rolls:{critRate:8.4,critDmg:16.8,statPct:9,dmg:9,flatAtk:45,flatHp:450,flatDef:55},party:{carry:null,mate2:null,mate3:null}};
const opts=(a,v)=>a.map(([x,l])=>`<option value="${x}" ${x===v?'selected':''}>${l}</option>`).join('');
async function loadRoster(){try{const r=await fetch('/wuwa/data/characters.json',{cache:'no-store'});if(!r.ok)throw 0;const j=await r.json();const arr=Array.isArray(j)?j:j.characters;if(!Array.isArray(arr)||!arr.length)throw 0;roster=arr.filter(x=>x&&x.name).map((x,i)=>({id:String(x.id||i),name:String(x.name).trim(),image:x.image||x.icon||x.cover||'',source:x.source||'kurobbs'}));$('rosterSource').textContent=`库街区角色库 · ${roster.length} 名角色`;}catch(e){roster=FALLBACK;$('rosterSource').textContent='库街区角色名单快照 · 图片数据更新中';}renderCharacters();}
function avatar(c,cls='portrait'){if(c?.image)return `<span class="${cls}"><img src="${esc(c.image)}" alt="${esc(c.name)}" loading="lazy" referrerpolicy="no-referrer" onerror="this.parentElement.textContent='${esc(c.name.slice(0,1))}'"></span>`;return `<span class="${cls} placeholder">${esc((c?.name||'?').slice(0,1))}</span>`}
function setParty(slot,c){M.party[slot]=c?{id:c.id,name:c.name,image:c.image}:null;const b=document.querySelector(`[data-slot="${slot}"]`);if(!b)return;b.innerHTML=`${avatar(c)}<span class="pick-name" id="${slot}Name">${esc(c?.name||'选择角色')}</span>`;buffRows();}
function renderCharacters(filter=''){const q=filter.trim().toLowerCase();$('characterGrid').innerHTML=roster.filter(c=>!q||c.name.toLowerCase().includes(q)).map(c=>`<button class="character-card" data-char-id="${esc(c.id)}" type="button">${avatar(c)}<span>${esc(c.name)}</span></button>`).join('');}
function openPicker(slot){pickSlot=slot;$('characterBrowser').hidden=false;renderCharacters($('characterSearch').value);$('characterBrowser').scrollIntoView({behavior:'smooth',block:'nearest'});}
function setAdvanced(v){advanced=!!v;document.body.classList.toggle('advanced-enabled',advanced);$('advancedMode').checked=advanced;$('advancedState').textContent=advanced?'已开启':'未开启';$('advancedToggle').classList.toggle('active',advanced);$('simpleModeCard').classList.toggle('active',!advanced);$('modeResult').textContent=advanced?'高级配队模式':'普通模式';calculate();}
function initTypes(){$('typeBonusGrid').innerHTML=DT.map(([k,l])=>`<div class="type-bonus-row"><span>${l}</span><label>加成 %<input id="dmg_${k}" type="number" value="0" step="0.1"></label><label>Amplify %<input id="amp_${k}" type="number" value="0" step="0.1"></label></div>`).join('')}
function echoRows(w){let a=w==='old'?M.oldEcho:M.newEcho;while(a.length<5)a.push({type:'',value:0});a=a.slice(0,5);if(w==='old')M.oldEcho=a;else M.newEcho=a;$(w+'EchoRows').innerHTML=a.map((r,i)=>`<div class="echo-row" data-i="${i}"><select class="echo-type">${opts(SS,r.type)}</select><input class="echo-value" type="number" step="0.1" value="${r.value||0}"><button class="icon-btn clear-line" type="button">×</button></div>`).join('')}
function sourceOpts(v){const a=[['self',M.party.carry?.name||'主角色'],['mate2',M.party.mate2?.name||'队友2'],['mate3',M.party.mate3?.name||'队友3'],['other','其他']];return opts(a,v)}
function buffRows(){$('buffRows').innerHTML=M.buffs.map((b,i)=>`<tr data-i="${i}"><td><select class="buff-source">${sourceOpts(b.source)}</select></td><td><input class="buff-name" value="${esc(b.name)}"></td><td><select class="buff-effect">${opts(BE,b.effect)}</select></td><td><input class="buff-value" type="number" step="0.1" value="${b.value}"></td><td><select class="buff-target" ${['dmgBonus','amplify'].includes(b.effect)?'':'disabled'}>${opts([['all','全部伤害'],...DT],b.target||'all')}</select></td><td><button class="icon-btn delete-buff" type="button">×</button></td></tr>`).join('');segRows()}
function segRows(){$('segmentRows').innerHTML=M.segments.map((s,i)=>`<div class="segment-card" data-i="${i}"><div class="segment-top"><label>窗口名称<input class="seg-name" value="${esc(s.name)}"></label><label>伤害类型<select class="seg-type">${opts(DT,s.type)}</select></label><label>倍率属性<select class="seg-scaler">${opts(SC,s.scaler)}</select></label><label>占比 %<input class="seg-share" type="number" step="0.1" value="${s.share}"></label><button class="icon-btn delete-seg" type="button">×</button></div><div class="segment-buffs"><button class="buff-chip ${s.canCrit?'active':''}" data-crit="1" type="button">${s.canCrit?'✓ ':''}可暴击</button>${M.buffs.map(b=>`<button class="buff-chip ${s.buffs.includes(b.id)?'active':''}" data-bid="${b.id}" type="button">${s.buffs.includes(b.id)?'✓ ':''}${esc(b.name)}</button>`).join('')}</div></div>`).join('');coverage()}
function coverage(){if(!advanced){$('coverageSummary').innerHTML='';return}const t=M.segments.reduce((a,s)=>a+Math.max(0,+s.share||0),0)||1;$('coverageSummary').innerHTML=M.buffs.map(b=>{const x=M.segments.filter(s=>s.buffs.includes(b.id)).reduce((a,s)=>a+Math.max(0,+s.share||0),0);return `<span class="coverage-item">${esc(b.name)} 覆盖 <b>${(x/t*100).toFixed(1)}%</b></span>`}).join('')}
function rollUI(){const r=M.rolls;$('rollControls').innerHTML=[['critRate','标准暴击 %'],['critDmg','标准暴伤 %'],['statPct','标准属性%'],['dmg','标准类型伤 %'],['flatAtk','标准小攻击'],['flatHp','标准小生命'],['flatDef','标准小防御']].map(([k,l])=>`<label>${l}<input class="roll-input" data-roll="${k}" type="number" step="0.1" value="${r[k]}"></label>`).join('')}
function pullEcho(w){M[w+'Echo']=[...$(w+'EchoRows').querySelectorAll('.echo-row')].map(r=>({type:r.querySelector('.echo-type').value,value:+r.querySelector('.echo-value').value||0}))}
function pullAdvanced(){if(!advanced)return;[...$('buffRows').querySelectorAll('tr')].forEach((r,i)=>Object.assign(M.buffs[i],{source:r.querySelector('.buff-source').value,name:r.querySelector('.buff-name').value,effect:r.querySelector('.buff-effect').value,value:+r.querySelector('.buff-value').value||0,target:r.querySelector('.buff-target').value||'all'}));[...$('segmentRows').querySelectorAll('.segment-card')].forEach((r,i)=>Object.assign(M.segments[i],{name:r.querySelector('.seg-name').value,type:r.querySelector('.seg-type').value,scaler:r.querySelector('.seg-scaler').value,share:+r.querySelector('.seg-share').value||0}))}
function state(){const td={},ta={};DT.forEach(([k])=>{td[k]=num('dmg_'+k);ta[k]=num('amp_'+k)});return{base:{atk:num('baseAtk'),hp:num('baseHp'),def:num('baseDef')},total:{atk:num('totalAtk'),hp:num('totalHp'),def:num('totalDef')},critRate:num('critRate'),critDmg:num('critDmg'),energyRegen:num('energyRegen'),globalDmg:num('globalDmg'),globalAmp:num('globalAmp'),typeDmg:td,typeAmp:ta}}
function sub(s,t,v,sg=1){v*=sg;if(!t||!v)return s;if(t==='atkPct')s.total.atk+=s.base.atk*v/100;else if(t==='flatAtk')s.total.atk+=v;else if(t==='hpPct')s.total.hp+=s.base.hp*v/100;else if(t==='flatHp')s.total.hp+=v;else if(t==='defPct')s.total.def+=s.base.def*v/100;else if(t==='flatDef')s.total.def+=v;else if(t==='critRate')s.critRate+=v;else if(t==='critDmg')s.critDmg+=v;else if(t==='energyRegen')s.energyRegen+=v;else if(t==='basicDmg')s.typeDmg.basic+=v;else if(t==='heavyDmg')s.typeDmg.heavy+=v;else if(t==='skillDmg')s.typeDmg.skill+=v;else if(t==='liberationDmg')s.typeDmg.liberation+=v;return s}
function replaced(panel,echo){const s=clone(panel);M.oldEcho.forEach(r=>sub(s,r.type,r.value,-1));echo.forEach(r=>sub(s,r.type,r.value));return s}
function applyBuffs(s,seg){s=clone(s);if(!advanced)return s;M.buffs.forEach(b=>{if(!seg.buffs.includes(b.id))return;const v=+b.value||0;if(b.effect==='atkPct')s.total.atk+=s.base.atk*v/100;else if(b.effect==='flatAtk')s.total.atk+=v;else if(b.effect==='hpPct')s.total.hp+=s.base.hp*v/100;else if(b.effect==='flatHp')s.total.hp+=v;else if(b.effect==='defPct')s.total.def+=s.base.def*v/100;else if(b.effect==='flatDef')s.total.def+=v;else if(b.effect==='critRate')s.critRate+=v;else if(b.effect==='critDmg')s.critDmg+=v;else if(b.effect==='energyRegen')s.energyRegen+=v;else if(b.effect==='dmgBonus'){if(b.target==='all')s.globalDmg+=v;else s.typeDmg[b.target]=(s.typeDmg[b.target]||0)+v}else if(b.effect==='amplify'){if(b.target==='all')s.globalAmp+=v;else s.typeAmp[b.target]=(s.typeAmp[b.target]||0)+v}});return s}
function windows(){if(!advanced)return[{id:'simple',name:'普通模式',type:'other',scaler:'atk',share:100,w:1,canCrit:true,buffs:[]}];const a=M.segments.map(s=>({...s,share:Math.max(0,+s.share||0)})),t=a.reduce((x,s)=>x+s.share,0);return t?a.map(s=>({...s,w:s.share/t})):[]}
function factor(s,g){s=applyBuffs(s,g);const stat=Math.max(1e-6,s.total[g.scaler]),dmg=Math.max(1e-6,1+(s.globalDmg+(s.typeDmg[g.type]||0))/100),amp=Math.max(1e-6,1+(s.globalAmp+(s.typeAmp[g.type]||0))/100),cr=clamp(s.critRate/100,0,1),cd=Math.max(1,s.critDmg/100),crit=g.canCrit?1+cr*(cd-1):1;return stat*dmg*amp*crit}
function compare(a,b){let ratio=0;const details=windows().map(g=>{const r=factor(b,g)/factor(a,g);ratio+=g.w*r;return{label:g.name,value:(r-1)*100}});return{gain:(ratio-1)*100,details}}
function singleGain(base,t,v){const c=clone(base);sub(c,t,v);return compare(base,c).gain}
function bars(root,a){const mx=Math.max(.01,...a.map(x=>Math.abs(x.value)));root.innerHTML=a.map(x=>`<div class="bar-row ${x.value<0?'negative':''}"><div class="bar-label">${esc(x.label)}</div><div class="bar-track"><div class="bar-fill" style="width:${Math.min(100,Math.abs(x.value)/mx*100)}%"></div></div><div class="bar-value">${fmt(x.value)}</div></div>`).join('')||'<div class="micro">暂无数据。</div>'}
function standards(cur){const r=M.rolls;return[['critRate',r.critRate,`暴击 ${r.critRate}%`],['critDmg',r.critDmg,`暴伤 ${r.critDmg}%`],['atkPct',r.statPct,`大攻击 ${r.statPct}%`],['flatAtk',r.flatAtk,`小攻击 ${r.flatAtk}`],['hpPct',r.statPct,`大生命 ${r.statPct}%`],['defPct',r.statPct,`大防御 ${r.statPct}%`],['skillDmg',r.dmg,`技能伤 ${r.dmg}%`],['liberationDmg',r.dmg,`解放伤 ${r.dmg}%`]].map(([type,val,label])=>({type,val,label,value:singleGain(cur,type,val)})).sort((a,b)=>b.value-a.value)}
function boundaries(cur){const r=M.rolls,cr=clamp(cur.critRate/100,0,1);const cd=cur.critDmg/100;const gCD=singleGain(cur,'critDmg',r.critDmg),gCR=singleGain(cur,'critRate',r.critRate),gATK=singleGain(cur,'atkPct',r.statPct);$('boundaryCards').innerHTML=`<div class="boundary-card"><span>当前双暴关系</span><strong>${cur.critRate.toFixed(1)} / ${cur.critDmg.toFixed(1)}</strong><span>当前一条标准暴击 ${fmt(gCR)}；标准暴伤 ${fmt(gCD)}。</span></div><div class="boundary-card"><span>爆伤 vs 大攻击</span><strong>${gCD>gATK?'爆伤当前更高':'大攻击当前更高'}</strong><span>标准暴伤 ${fmt(gCD)} · 标准大攻击 ${fmt(gATK)}。角色/队伍自拐爆伤越高，爆伤边际收益通常继续下降。</span></div><div class="boundary-card"><span>期望暴击乘区</span><strong>${(1+cr*(Math.max(1,cd)-1)).toFixed(4)}</strong><span>CR 超过 100% 的部分按 0 边际收益处理。</span></div>`}
function calculate(){pullEcho('old');pullEcho('new');pullAdvanced();const p=state(),old=replaced(p,M.oldEcho),neu=replaced(p,M.newEcho),c=compare(old,neu);$('overallGain').textContent=fmt(c.gain);const cr=clamp(old.critRate/100,0,1),cd=Math.max(1,old.critDmg/100);$('critFactor').textContent=(1+cr*(cd-1)).toFixed(4);$('critState').textContent=`${old.critRate.toFixed(1)}% CR / ${old.critDmg.toFixed(1)}% CD`;$('candidateEr').textContent=`${neu.energyRegen.toFixed(1)}%`;const s=standards(old);$('bestStandard').textContent=s[0]?.label||'—';bars($('standardBars'),s);const lines=M.newEcho.filter(r=>r.type&&r.value).map(r=>{const base=clone(neu);sub(base,r.type,r.value,-1);return{label:`${SL[r.type]||r.type} ${r.value}`,value:compare(base,neu).gain}});bars($('lineMarginals'),lines);bars($('segmentResultBars'),c.details);boundaries(old);coverage()}
function bind(){document.querySelectorAll('.character-pick').forEach(b=>b.onclick=()=>openPicker(b.dataset.slot));$('closeCharacterBrowser').onclick=()=>{$('characterBrowser').hidden=true};$('characterSearch').oninput=e=>renderCharacters(e.target.value);$('characterGrid').onclick=e=>{const b=e.target.closest('[data-char-id]');if(!b)return;const c=roster.find(x=>x.id===b.dataset.charId);if(c){setParty(pickSlot,c);$('characterBrowser').hidden=true}};$('advancedToggle').onclick=()=>setAdvanced(!advanced);$('simpleModeCard').onclick=()=>setAdvanced(false);$('calculateBtn').onclick=calculate;$('resetStatsBtn').onclick=()=>{[['baseAtk',950],['totalAtk',2300],['baseHp',15000],['totalHp',21000],['baseDef',1200],['totalDef',1500],['critRate',75],['critDmg',250],['energyRegen',125],['globalDmg',60],['globalAmp',0]].forEach(([id,v])=>$(id).value=v);calculate()};document.body.addEventListener('input',e=>{if(e.target.matches('.echo-type,.echo-value,.roll-input,#baseAtk,#totalAtk,#baseHp,#totalHp,#baseDef,#totalDef,#critRate,#critDmg,#energyRegen,#globalDmg,#globalAmp,[id^="dmg_"],[id^="amp_"]')){if(e.target.matches('.roll-input'))M.rolls[e.target.dataset.roll]=+e.target.value||0;calculate()}});document.body.addEventListener('change',e=>{if(e.target.matches('.echo-type,.buff-effect,.buff-source,.buff-target,.seg-type,.seg-scaler'))calculate()});document.body.addEventListener('click',e=>{let b=e.target.closest('[data-clear-echo]');if(b){M[b.dataset.clearEcho+'Echo']=Array(5).fill(0).map(()=>({type:'',value:0}));echoRows(b.dataset.clearEcho);calculate();return}b=e.target.closest('.clear-line');if(b){const row=b.closest('.echo-row');row.querySelector('.echo-type').value='';row.querySelector('.echo-value').value=0;calculate();return}b=e.target.closest('.delete-buff');if(b){M.buffs.splice(+b.closest('tr').dataset.i,1);buffRows();calculate();return}b=e.target.closest('.delete-seg');if(b){M.segments.splice(+b.closest('.segment-card').dataset.i,1);segRows();calculate();return}b=e.target.closest('.buff-chip');if(b){const card=b.closest('.segment-card'),s=M.segments[+card.dataset.i];if(b.dataset.crit){s.canCrit=!s.canCrit}else{const id=b.dataset.bid;s.buffs=s.buffs.includes(id)?s.buffs.filter(x=>x!==id):[...s.buffs,id]}segRows();calculate()}});$('addBuffBtn').onclick=()=>{M.buffs.push({id:'b'+Date.now(),source:'mate2',name:'新 Buff',effect:'atkPct',value:20,target:'all'});buffRows()};$('addSegmentBtn').onclick=()=>{M.segments.push({id:'s'+Date.now(),name:'新窗口',type:'skill',scaler:'atk',share:0,canCrit:true,buffs:[]});segRows()};$('normalizeSegmentsBtn').onclick=()=>{const t=M.segments.reduce((a,s)=>a+(+s.share||0),0);if(t)M.segments.forEach(s=>s.share=(+s.share||0)/t*100);segRows();calculate()}}
initTypes();echoRows('old');echoRows('new');buffRows();rollUI();bind();setAdvanced(false);loadRoster().then(()=>calculate());
})();
