(()=>{'use strict';
if(window.__wuwaProfileSaveV6Loaded)return;window.__wuwaProfileSaveV6Loaded=true;
const KEY='wuwaEchoBuildProfilesV6';
const LEGACY=['wuwaEchoBuildProfilesV5','wuwaEchoBuildProfilesV4','wuwaEchoBuildProfilesV3','wuwaEchoBuildProfilesV2'];
const $=id=>document.getElementById(id),wait=ms=>new Promise(r=>setTimeout(r,ms)),fire=(e,t='change')=>e&&e.dispatchEvent(new Event(t,{bubbles:true}));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function read(k=KEY){try{return JSON.parse(localStorage.getItem(k)||'{}')||{}}catch{return{}}}
function store(){let s=read();if(Object.keys(s).length)return s;for(const k of LEGACY){s=read(k);if(Object.keys(s).length){localStorage.setItem(KEY,JSON.stringify(s));return s}}return{}}
function write(s){localStorage.setItem(KEY,JSON.stringify(s))}
function char(){const n=$('characterName')?.textContent?.trim();return n&&n!=='选择角色'?n:''}
function status(t){if($('wuwaSaveStatus'))$('wuwaSaveStatus').textContent=t}
function readEcho(c){return{cost:+c.querySelector('.echo-cost')?.value||4,mainType:c.querySelector('.main-primary .echo-type')?.value||'',sub:[...c.querySelectorAll('.sub-rows .echo-row')].map(r=>({type:r.querySelector('.echo-type')?.value||'',value:+r.querySelector('.echo-value')?.value||0}))}}
function snapshot(){const n=char();if(!n)return null;const stats={};['totalAtk','totalHp','totalDef','critRate','critDmg','energyRegen','elementDmg','globalDmg','globalAmp','nonEchoAtkPct','nonEchoHpPct','nonEchoDefPct'].forEach(id=>stats[id]=+$(id)?.value||0);return{version:6,characterName:n,chainLevel:+$('chainLevel')?.value||0,scaler:$('scaler')?.value||'atk',gear:{weaponMode:$('weaponMode')?.value||'none',sonataMain:$('sonataMain')?.value||'',sonataPieces:$('sonataPieces')?.value||'none',sonataSecondary:$('sonataSecondary')?.value||''},stats,echoes:[...document.querySelectorAll('#equippedEchoes .echo-card')].map(readEcho),savedAt:new Date().toISOString()}}
function refresh(prefer=''){const el=$('wuwaSavedBuilds');if(!el)return;const s=store(),names=Object.keys(s).sort((a,b)=>a.localeCompare(b,'zh-CN'));el.innerHTML='<option value="">— 已保存角色 —</option>'+names.map(n=>`<option value="${esc(n)}">${esc(n)}</option>`).join('');if(prefer&&s[prefer])el.value=prefer;if(!prefer)status(char()&&s[char()]?'该角色已有本机保存配置':'配置仅保存在当前浏览器')}
async function choose(n){if(char()===n)return true;$('characterPick')?.click();await wait(50);const q=$('characterSearch');if(q){q.value=n;fire(q,'input');await wait(30)}const b=[...document.querySelectorAll('#characterGrid .character-card')].find(x=>x.textContent.includes(n));if(!b)return false;b.click();await wait(80);return true}
async function restoreEcho(c,d){if(!c||!d)return;const cost=c.querySelector('.echo-cost');if(cost){cost.value=String(d.cost||4);fire(cost);await wait(0)}const main=c.querySelector('.main-primary .echo-type');if(main){main.value=d.mainType||'';fire(main);await wait(0)}const rows=[...c.querySelectorAll('.sub-rows .echo-row')];for(let i=0;i<rows.length;i++){const v=d.sub?.[i]||{type:'',value:0},t=rows[i].querySelector('.echo-type');if(t){t.value=v.type||'';fire(t);await wait(0)}const val=rows[i].querySelector('.echo-value');if(val&&v.type){val.value=String(v.value||0);fire(val)}}}
function normalizeGear(g={}){if(g.sonataPieces)return{weaponMode:g.weaponMode||'none',sonataMain:g.sonataMain||'',sonataPieces:String(g.sonataPieces),sonataSecondary:g.sonataSecondary||''};if(g.sonataBuildMode){const pieceMap={five:'5',threeTwo:'3',one:'1',none:'none'};return{weaponMode:g.weaponMode||'none',sonataMain:g.sonataMain||'',sonataPieces:pieceMap[g.sonataBuildMode]||'none',sonataSecondary:g.sonataSecondary||''}}const old=g.sonataMode||'',map={eternal5:['此间永驻之光','5'],lingering5:['不绝余音','5'],rejuv5:['隐世回光','5'],eternal2:['','none'],lingering2:['','none'],moonlit2:['','none']},m=map[old]||['','none'];return{weaponMode:g.weaponMode||'none',sonataMain:m[0],sonataPieces:m[1],sonataSecondary:''}}
async function restoreGear(g){const weapon=$('weaponMode');if(weapon){weapon.value=g.weaponMode||'none';fire(weapon)}const main=$('sonataMain');if(main){main.value=g.sonataMain||'';fire(main);await wait(0)}const pieces=$('sonataPieces');if(pieces){const wanted=String(g.sonataPieces||'none');if([...pieces.options].some(o=>o.value===wanted))pieces.value=wanted;fire(pieces);await wait(0)}const secondary=$('sonataSecondary');if(secondary&&!secondary.disabled){secondary.value=g.sonataSecondary||'';fire(secondary)}}
async function load(n){const p=store()[n];if(!p)return;status('正在载入…');if(!(await choose(p.characterName||n))){status('找不到该角色，载入失败');return}if($('chainLevel')){$('chainLevel').value=String(p.chainLevel??0);fire($('chainLevel'))}if($('scaler')&&!$('scaler').disabled&&p.scaler){$('scaler').value=p.scaler;fire($('scaler'))}await restoreGear(normalizeGear(p.gear||{}));Object.entries(p.stats||{}).forEach(([id,v])=>{const e=$(id);if(e){e.value=String(v);fire(e,'input')}});const cards=[...document.querySelectorAll('#equippedEchoes .echo-card')];for(let i=0;i<cards.length;i++)await restoreEcho(cards[i],p.echoes?.[i]);await wait(30);$('calculateBtn')?.click();refresh(n);status(`已载入 ${n} 的配置`)}
function save(){const p=snapshot();if(!p){status('请先选择角色');return}const s=store();s[p.characterName]=p;write(s);refresh(p.characterName);status(`已保存 ${p.characterName} · ${p.chainLevel}链`)}
function del(){const n=$('wuwaSavedBuilds')?.value||char();if(!n)return;const s=store();delete s[n];write(s);refresh();status(`已删除 ${n} 的本机配置`)}
function mount(){if($('wuwaLocalSaveBar'))return;const host=document.querySelector('.intro-panel .profile-grid');if(!host)return;const box=document.createElement('div');box.id='wuwaLocalSaveBar';box.className='wuwa-local-save';box.innerHTML=`<div class="wuwa-save-head"><strong>角色配置保存</strong><span id="wuwaSaveStatus">配置仅保存在当前浏览器</span></div><div class="wuwa-save-actions"><select id="wuwaSavedBuilds"><option value="">— 已保存角色 —</option></select><button type="button" id="wuwaSaveCurrent">保存当前配置</button><button type="button" id="wuwaLoadSaved">载入</button><button type="button" id="wuwaDeleteSaved" class="danger-lite">删除</button></div>`;host.insertAdjacentElement('afterend',box);$('wuwaSaveCurrent').onclick=save;$('wuwaLoadSaved').onclick=()=>{const n=$('wuwaSavedBuilds').value;if(n)load(n)};$('wuwaDeleteSaved').onclick=del;refresh()}
function css(){if($('wuwa-profile-v6-style'))return;const s=document.createElement('style');s.id='wuwa-profile-v6-style';s.textContent='.wuwa-local-save{margin:12px 0 4px;padding:12px;border:1px solid var(--line);border-radius:12px;background:var(--panel2)}.wuwa-save-head{display:flex;justify-content:space-between;gap:10px;margin-bottom:9px}.wuwa-save-head strong{font-size:13px}.wuwa-save-head span{font-size:11px;color:var(--muted)}.wuwa-save-actions{display:grid;grid-template-columns:minmax(180px,1fr) auto auto auto;gap:8px}.wuwa-save-actions select,.wuwa-save-actions button{min-height:38px;border:1px solid var(--line);border-radius:9px;background:var(--panel);color:var(--text);padding:0 11px}.wuwa-save-actions button{font-weight:700;cursor:pointer}@media(max-width:650px){.wuwa-save-head{flex-direction:column}.wuwa-save-actions{grid-template-columns:1fr 1fr}.wuwa-save-actions select{grid-column:1/-1}}';document.head.appendChild(s)}
function init(){css();mount();new MutationObserver(mount).observe(document.body,{childList:true,subtree:true});document.addEventListener('click',e=>{if(e.target.closest?.('.character-card'))setTimeout(()=>refresh(char()),120)})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();